-- ============================================================
-- NUSP — Dados iniciais (seed)
-- Salas, comissões e usuários de teste
-- ============================================================

-- CAD_SALA (10 salas do Senado)
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (1, 'Auditório Petrônio Portella', 1, SYSTIMESTAMP, SYSTIMESTAMP, 1);
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (2, 'Plenário', 1, SYSTIMESTAMP, SYSTIMESTAMP, 2);
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (3, 'Plenário 02', 1, SYSTIMESTAMP, SYSTIMESTAMP, 3);
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (4, 'Plenário 03', 1, SYSTIMESTAMP, SYSTIMESTAMP, 4);
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (5, 'Plenário 06', 1, SYSTIMESTAMP, SYSTIMESTAMP, 5);
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (6, 'Plenário 07', 1, SYSTIMESTAMP, SYSTIMESTAMP, 6);
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (7, 'Plenário 09', 1, SYSTIMESTAMP, SYSTIMESTAMP, 7);
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (8, 'Plenário 13', 1, SYSTIMESTAMP, SYSTIMESTAMP, 8);
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (9, 'Plenário 15', 1, SYSTIMESTAMP, SYSTIMESTAMP, 9);
INSERT INTO CAD_SALA (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (10, 'Plenário 19', 1, SYSTIMESTAMP, SYSTIMESTAMP, 10);

-- CAD_COMISSAO (30 comissões)
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (1, 'CAE - Comissão de Assuntos Econômicos', 1, SYSTIMESTAMP, SYSTIMESTAMP, 1);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (2, 'CAS - Comissão de Assuntos Sociais', 1, SYSTIMESTAMP, SYSTIMESTAMP, 2);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (3, 'CCDD - Comissão de Comunicação e Direito Digital', 1, SYSTIMESTAMP, SYSTIMESTAMP, 3);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (4, 'CCJ - Comissão de Constituição, Justiça e Cidadania', 1, SYSTIMESTAMP, SYSTIMESTAMP, 4);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (5, 'CCT - Comissão de Ciência, Tecnologia, Inovação e Informática', 1, SYSTIMESTAMP, SYSTIMESTAMP, 5);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (6, 'CDD - Comissão de Defesa da Democracia', 1, SYSTIMESTAMP, SYSTIMESTAMP, 6);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (7, 'CDH - Comissão de Direitos Humanos e Legislação Participativa', 1, SYSTIMESTAMP, SYSTIMESTAMP, 7);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (8, 'CDIR - Comissão Diretora do Senado Federal', 1, SYSTIMESTAMP, SYSTIMESTAMP, 8);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (9, 'CDR - Comissão de Desenvolvimento Regional e Turismo', 1, SYSTIMESTAMP, SYSTIMESTAMP, 9);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (10, 'CE - Comissão de Educação e Cultura', 1, SYSTIMESTAMP, SYSTIMESTAMP, 10);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (11, 'CEsp - Comissão de Esporte', 1, SYSTIMESTAMP, SYSTIMESTAMP, 11);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (12, 'CI - Comissão de Serviços de Infraestrutura', 1, SYSTIMESTAMP, SYSTIMESTAMP, 12);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (13, 'CMA - Comissão de Meio Ambiente', 1, SYSTIMESTAMP, SYSTIMESTAMP, 13);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (14, 'CRA - Comissão de Agricultura e Reforma Agrária', 1, SYSTIMESTAMP, SYSTIMESTAMP, 14);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (15, 'CRE - Comissão de Relações Exteriores e Defesa Nacional', 1, SYSTIMESTAMP, SYSTIMESTAMP, 15);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (16, 'CSP - Comissão de Segurança Pública', 1, SYSTIMESTAMP, SYSTIMESTAMP, 16);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (17, 'CTFC - Comissão de Transparência, Governança, Fiscalização e Controle e Defesa do Consumidor', 1, SYSTIMESTAMP, SYSTIMESTAMP, 17);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (18, 'CCAI - Comissão Mista de Controle das Atividades de Inteligência', 1, SYSTIMESTAMP, SYSTIMESTAMP, 19);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (19, 'CMCVM - Comissão Permanente Mista de Combate à Violência contra a Mulher', 1, SYSTIMESTAMP, SYSTIMESTAMP, 20);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (20, 'CMMC - Comissão Mista Permanente sobre Mudanças Climáticas', 1, SYSTIMESTAMP, SYSTIMESTAMP, 21);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (21, 'CMMIR - Comissão Mista Permanente sobre Migrações Internacionais e Refugiados', 1, SYSTIMESTAMP, SYSTIMESTAMP, 22);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (22, 'CMO - Comissão Mista de Planos, Orçamentos Públicos e Fiscalização', 1, SYSTIMESTAMP, SYSTIMESTAMP, 23);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (23, 'CPI - Comissão Parlamentar de Inquérito', 1, SYSTIMESTAMP, SYSTIMESTAMP, 24);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (24, 'CPMI - Comissão Parlamentar Mista de Inquérito', 1, SYSTIMESTAMP, SYSTIMESTAMP, 25);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (25, 'CT - Comissão Temporária', 1, SYSTIMESTAMP, SYSTIMESTAMP, 26);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (26, 'cessão - Cessão de Sala', 1, SYSTIMESTAMP, SYSTIMESTAMP, 28);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (27, 'outros - Outros Eventos', 1, SYSTIMESTAMP, SYSTIMESTAMP, 29);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (28, 'GP - Grupo Parlamentar', 1, SYSTIMESTAMP, SYSTIMESTAMP, 27);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (29, 'GP - Grupo Parlamentar', 0, SYSTIMESTAMP, SYSTIMESTAMP, NULL);
INSERT INTO CAD_COMISSAO (ID, NOME, ATIVO, CRIADO_EM, ATUALIZADO_EM, ORDEM) VALUES (30, 'CMMPV  - Comissão Mista de Medida Provisória', 1, SYSTIMESTAMP, SYSTIMESTAMP, 18);

-- PES_ADMINISTRADOR (usuário de teste — login: admin / senha: admin)
INSERT INTO PES_ADMINISTRADOR (ID, NOME_COMPLETO, EMAIL, USERNAME, PASSWORD_HASH, CRIADO_EM, ATUALIZADO_EM)
VALUES (SYS_GUID(), 'Administrador Teste', 'admin@teste.com', 'admin', '$2b$10$qwt5UpvFa40Yp0pQRd/PlOgB4oyHUIaix545mKTaDI5m3Nkcwsbbm', SYSTIMESTAMP, SYSTIMESTAMP);

-- PES_OPERADOR (usuário de teste — login: operador / senha: 1234)
INSERT INTO PES_OPERADOR (ID, NOME_COMPLETO, NOME_EXIBICAO, EMAIL, USERNAME, PASSWORD_HASH, CRIADO_EM, ATUALIZADO_EM)
VALUES (SYS_GUID(), 'Operador Teste', 'Operador', 'operador@teste.com', 'operador', '$2b$10$WpfoU53C4Ha0Ra1/jQIAz.wV47s0NNrteJnp6DsGany5lytatF64C', SYSTIMESTAMP, SYSTIMESTAMP);

COMMIT;
